# Generated by Django 3.0.8 on 2020-10-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post1',
        ),
    ]
