# Generated by Django 3.0.8 on 2020-10-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0002_auto_20201009_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPost',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('author', models.TextField()),
                ('total_cm', models.CharField(max_length=255)),
                ('total_like', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
