# Generated by Django 3.0.8 on 2020-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0003_auto_20201012_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('image_filename', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
