# Generated by Django 3.1.3 on 2020-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0006_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('hash', models.TextField()),
                ('status', models.TextField()),
                ('time_to_push', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('password', models.TextField()),
                ('host', models.TextField()),
                ('schedule', models.IntegerField()),
            ],
        ),
    ]
