# Generated by Django 3.1.3 on 2020-11-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0006_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('hash', models.TextField()),
                ('status', models.TextField()),
                ('time_to_push', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('password', models.TextField()),
                ('host', models.TextField()),
                ('schedule', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spost2',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('image_filename', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spost3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('image_filename', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spost4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('image_filename', models.TextField()),
                ('title', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='spost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
