# Generated by Django 3.1.3 on 2020-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0007_file_info_ftp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
