# Generated by Django 3.1.3 on 2020-11-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0008_auto_20201123_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spost2',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('image_filename', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
