# Generated by Django 3.1.3 on 2020-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vul_web', '0009_spost2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spost3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('image_filename', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
